@apiLocal = http://localhost:3000

@apiVercel = https://farmax.vercel.app


###
GET {{apiVercel}}/api/products

###
POST {{apiLocal}}/api/products
Content-type: application/json

 {
    "name": "migral vi",
    "price": 800,
    "image": "5",
    "stock": 9,
    "expires": "12/10/2025",
    "laboratories": ["martinez", "rodriguez"],
    "categoryId": "632e59669b026568ad8abbce"
 }

###
POST {{apiVercel}}/api/forgot
Content-type: application/json

 {
    "email": "lucano@gmail.com",
    "password": 800
 }


###
PUT {{apiLocal}}/api/productos/6331e674b55387020b7f469e 
Content-type: application/json

 {
    "name": "hamburguesas",
    "price": 97,
    "image": "3",
    "categoryId": "632e59669b026568ad8abbce"
 }


###
DELETE https://zafirus-c.herokuapp.com/users/62c2249fe35b235a0161368b

