@apiLocal = http://localhost:3000

@apiVercel = https://farmax.vercel.app/


###
GET {{apiLocal}}/api/products

###
POST {{apiLocal}}/api/products
Content-type: application/json

 {
    "name": "migral vi",
    "price": 800,
    "image": "5",
    "stock": 9,
    
    "laboratories": ["martinez", "rodriguez"],
    "categoryId": "632e59669b026568ad8abbce"
 }


###
PUT {{apiLocal}}/api/products/65f0b3e536d857aa5140c175 
Content-type: application/json

 {
    "name": "migral evop",
    "price": 60,
    "stock": 2,
    "laboratories": [1,2],
    "expires": "12-08-2020",
    "categoryId": "632e59669b026568ad8abbce"
 }


###
DELETE https://zafirus-c.herokuapp.com/users/62c2249fe35b235a0161368b

