@apiLocal = http://localhost:3000

@apiVercel = https://farmax.vercel.app/


###
POST {{apiLocal}}/api/auth/register
Content-type: application/json

 {
    "fullname": "luciano",
    "email": "lucano4@smail.com",
    "password": "luciano123"
 }



###
POST {{apiLocal}}/api/auth/login
Content-type: application/json

 {
    "email": "lucano4@smail.com",
    "password": "luciano123"
 }




###
GET {{apiLocal}}//api/auth/logout
Content-type: application/json



###
GET {{apiLocal}}/api/profile
Content-type: application/json

 {
    "email": "lucano@gmail.com",
    "password": "luciano123"
 }




###
PUT {{apiLocal}}/api/auth/forget
Content-type: application/json

 {
    "email": "lucano@smail.com"
 }