@apiLocal = http://localhost:3000

@apiVercel = https://farmax.vercel.app/


###
POST {{apiLocal}}/api/auth/register
Content-type: application/json

 {
    "fullname": "luciano",
    "email": "lucano3@smail.com",
    "password": "luciano123"
 }



###
POST {{apiLocal}}/api/auth/login
Content-type: application/json

 {
    "email": "lucano@smail.com",
    "password": "luciano123"
 }




###
GET {{apiLocal}}/api/auth/logout
Content-type: application/json



###
GET {{apiLocal}}/api/profile
Content-type: application/json

 {
    "email": "lucano@smail.com",
    "password": "luciano123"
 }




###
PUT {{apiLocal}}/api/auth/forget
Content-type: application/json

 {
    "email": "lucano3@smail.com"
 }



###
POST {{apiLocal}}/api/auth/verify
Content-type: application/json

 {
    "token": "f595438ecb8567a976e1a3885b1aacd5f49bb33d"
 }




###
POST {{apiLocal}}/api/auth/reset
Content-type: application/json

 {
    "email": "lucano3@smail.com",
    "password": "luciano321"
 }